apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx-test
  namespace: test
spec:
  containers:
  - image: nginx
    name: nginx1
    ports:
    - name: http
      containerPort: 80
    resources: {}
  - image: ghost
    name: ghost
    ports:
    - name: http
      containerPort: 2371 
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
